baseURL = "https://9lo.re/"
languageCode = "en"
title = "Hi, I'm ninelore!" # startpage header
theme = "hello-friend-ng"
paginate = 10

[params]
dateform = "2006-01-02"
dateformShort = "2006-01-02"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
disableReadOtherPosts = false
#enableSharingButtons = true

#homeSubtitle = "Just a human being..." # startpage subtitle

# Metadata mostly used in document's head
subtitle = "9lo.re" # tab title 2nd part
description = "ninelore's homepage" # ??
keywords = "homepage, personal, blog"
images = [""]
copyright = 'Content: <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a> | Code: <a href="https://www.gnu.org/licenses/agpl-3.0.en.html" target="_blank" rel="noopener">AGPL 3 only</a>'
readOtherPosts = "Read other posts"

[params.author]
name = "ninelore"

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[params.logo]
logoText = "9lo.re ~ $"
logoHomeLink = "/"

[params.footer]
copyright = true

topText = []
bottomText = []

[[params.social]]
name = "github"
url = "https://github.com/ninelore"

[[params.social]]
name = "email"
url = "mailto:9l@9lo.re"

[[params.social]]
name = "mastodon"
url = "https://donotsta.re/9lore"

#[[params.social]]
#name = "discord"
#url = "https://discord.gg/VSeCEVCTk6"


[languages]
[languages.en]
copyright = 'Content: <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a> | Code: <a href="https://www.gnu.org/licenses/agpl-3.0.en.html" target="_blank" rel="noopener">GNU AGPL 3.0</a>'

# And you can even create generic menu
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
